### ISSUE TITLE
Select subset of categories and other enhancements 

### ISSUE THREAD

**Issue by Sbozzolo** [GarrettBeatty/arXiv-eXplorer#23]
Hello,

I like the application, but at the moment it is lacking some features that I need if I want to replace my current workflow using arXiv-eXplorer.

I would like to be able to select some categories and ignore all the others. Then, I would like to see all the new papers of those categories collected in the same feed. It would also be nice if I could choose whether to show the abstract or not. 

This would replace my current solution: I have subscribed to the RSS feeds of some categories, I use a RSS reader to go through the new papers every day, and I save the papers I am interested in for later. 

Are there any plans to introduce the mentioned features?

Thank you,
sbozzolo.

**Comment by GarrettBeatty** [comment]
> I would like to be able to select some categories and ignore all the others. Then, I would like to see all the new papers of those categories collected in the same feed. It would also be nice if I could choose whether to show the abstract or not.

I can definitely implement this - a few questions for you though:

For choosing categories that you want to view, should it be general categories (astrophysics, computer science, etc) or specific categories (Artificial Intelligence, Computational Geometry) or have the ability to do select both?

Do you think this should be added as another tab on the bottom? Maybe have the tabs on the bottom be (browse, dashboard, favorites), where "dashboard" is your personalized feed idea?

-Garrett

**Comment by Sbozzolo** [comment]
I would love to have granularity. I follow hep-th, gr-qc, atro-ph, physics.pop-ph, but not physics.optics for example.

> Do you think this should be added as another tab on the bottom? Maybe have the tabs on the bottom be (browse, dashboard, favorites), where "dashboard" is your personalized feed idea?

Yes, it makes sense. 

Thank you for your efforts,
Sbozzolo

**Comment by GarrettBeatty** [comment]
Sounds good, I will work on this for the next app update, along with the other feature to show abstracts.

**Comment by GarrettBeatty** [comment]
@Sbozzolo I've added your suggestions and will be rolling out an update soon. Would you be willing to test an alpha version to see if it has the correct features (bug free hopefully). If so, can you provide me with your email (you can email me at garrettbdev@gmail.com or reply here with it) so I can add your account to the alpha testers list?
