### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by shernandezsantana** [GarrettBeatty/arXiv-eXplorer#43]
Since it is an open app, have you considered adding the app to F-Droid. If not, why not? I know some people do not use google services because of their personal reasons.

**Comment by GarrettBeatty** [comment]
I am currently in the process of adding it to F-droid. 

https://gitlab.com/fdroid/fdroiddata/merge_requests/4047

**Comment by GarrettBeatty** [comment]
https://f-droid.org/en/packages/com.gbeatty.arxiv/

It is now on fdroid.
