### ISSUE TITLE
Date formatting and paper numbering

### ISSUE THREAD

**Issue by GarrettBeatty** [GarrettBeatty/arXiv-eXplorer#47]
Would want to have the option to display date of papers in European rather than US format; meaning dd.mm.yyyy. And to have numbering of paper per day, for example if there are 20 papers today in some category, as I browse I could see 1/20, 2/20 etc, sort of a progress bar.

**Comment by GarrettBeatty** [comment]
Date formatting has been fixed

**Comment by physkets** [comment]
I'm using an Android 9 device with the time zone set to the Indian zone (I presume that is what sets locale). But the date displayed in the app is in the US format: mm.dd.yyyy . There is also no in-app setting to change this.
