### ISSUE TITLE
view/hide already seen paper

### ISSUE THREAD

**Issue by cerisara** [GarrettBeatty/arXiv-eXplorer#51]
I may have missed this feature, but my use of the app is to regularly check the abstract of the new papers, since the last time I've open the app. But as far as I know, the status of each paper (new, read, unread) is not saved in the app ? Or I've not found any option to show/hide the papers I've already seen ? (just like an RSS reader actually)

Thanks

**Comment by GarrettBeatty** [comment]
I agree with this. I was trying to think of a way to how to indicate that the paper/abstract has been read already.

If you have any suggestions  on how to. visually indicate the paper status, I am open to suggestions.

**Comment by mzattera** [comment]
My suggestion:

When tapping on an article this is considered read.

Add an icon on bottom right of the article, next to favorite icon. Tapping icon toggles read/unread state for the article.

On top right of the feed, next to the search icon, ad a "hide read icon". Tapping the icon toggles between show or hide read articles in the feed.

**Comment by mzattera** [comment]
Optionally, you can use a lighter text color or a different background color to help spotting the read articles in the feed in an easier way.

**Comment by GarrettBeatty** [comment]
Thanks for the suggestions. I will try to implement them when I get a chance.

**Comment by mzattera** [comment]
....any chance to finance this with a donation?

**Comment by mzattera** [comment]
https://m.freelancer.com/projects/mobile-phone/New-Feature-for-Open-Source

**Comment by GarrettBeatty** [comment]
I will try to get around to implementing the "read" feature this weekend - no donation is necessary.

**Comment by GarrettBeatty** [comment]
This feature should be done soon. I have it implemented, but I want to fix a few other bugs before I release the next update. :)

**Comment by mzattera** [comment]
Still, I will happy to make a contribution once it's rolled out.

**Comment by GarrettBeatty** [comment]
The update is live on the Google play store. If you want to donate there
is an in app purchase. If you are using the frdroid version, I still have
to push that update out
